export enum Formats {
  PERCENTAGE = 'PERCENTAGE',
  GROUPED_TWO_DIGITS = 'GROUPED_TWO_DIGITS',
  GROUPED_THOUSANDS_TWO_DIGITS = 'GROUPED_THOUSANDS_TWO_DIGITS',
  CURRENCY = 'CURRENCY',
  DAY_AND_MONTH = 'DAY_AND_MONTH',
  SHORT_MONTH = 'SHORT_MONTH',
  LARGE_MONTH = 'LARGE_MONTH',
  ANY = 'ANY'
}
